### ISSUE TITLE
How to use npm or any other program

### ISSUE THREAD

**Issue by kopax** [splattael/dind-example#1]
Hi, I see that you use the image `docker` for your container.

I am trying to setup a dind that include docker and npm. I wasn't able to reproduce it because this setup only work with `docker:latest`. 

By any chance, do you have any idea why ?

**Comment by splattael** [comment]
@kopax Hey! Can you provide a `docker-compose.yml`? :nerd_face:

**Comment by kopax** [comment]
I don't have one. The only solution I found for this was to create an extended Dockerfile `FROM docker`, otherwise, the dind will not work. 

The only annoying thing is that I must be on alpine linux is this docker image
